04 - Django/mainsite/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^url_short/', include('url_short.urls')),
    url(r'^library/', include('library.urls')),
]

04 - Django/mainsite/todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^savetodo/$', views.savetodo, name='savetodo'),
    url(r'^completetodo/$', views.completetodo, name='completetodo'),
]

04 - Django/mainsite/todo/models.py
from django.db import models


class TodoItem(models.Model):
    todo_text = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text + ' - ' + str(self.completed)

04 - Django/mainsite/todo/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import TodoItem

def index(request):

    todo_items = TodoItem.objects.filter(completed=False)
    completed_items = TodoItem.objects.filter(completed=True)

    context = {'todo_items': todo_items,
               'completed_items': completed_items}
    return render(request, 'todo/index.html', context)

def savetodo(request):

    todo_text = request.POST['todo_text']

    print(reverse('todo:index'))

    todo_item = TodoItem(todo_text=todo_text, completed=False)
    todo_item.save()

    return HttpResponseRedirect(reverse('todo:index'))

def completetodo(request):
    todo_id = request.POST['todo_id']
    todo_item = TodoItem.objects.get(pk=todo_id)
    todo_item.completed = True
    todo_item.save()
    return HttpResponseRedirect(reverse('todo:index'))

04 - Django/mainsite/todo/templates/todo/index.html
{% load static %}

<link  rel="stylesheet" type="text/css" href="{% static 'todo/style.css'%}"/>
<style>
    ul li:nth-child(odd) {
        background-color:lavender;
    }
    form {
        display:inline;
    }
    #completed_list li {
        text-decoration: line-through;
    }
</style>


<h1>Todo</h1>

<form action="{% url 'todo:savetodo' %}" method="post">
    {% csrf_token %}
    <input type="text" name="todo_text"/>
    <button type="submit">add todo</button>
</form>

<ul>
    {% for todo_item in todo_items %}
    <li>
        <form action="{% url 'todo:completetodo' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{ todo_item.id }}" name="todo_id"/>
            <button type="submit">✓</button>
        </form>
        <span>{{ todo_item.todo_text }}</span>
    </li>
    {% endfor %}
</ul>

<ul id="completed_list">
    {% for completed_item in completed_items %}
    <li>{{ completed_item.todo_text }}</li>
    {% endfor %}
</ul>