04 - Django/blogsite/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_page, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^post_list/$', views.post_list, name='post_list'),
    url(r'^post_detail/(?P<url_key>[0-9])/$', views.post_detail, name='post_detail'),
    url(r'^post_compose/$', views.post_compose, name='post_compose'),
    url(r'^post_blog/$', views.post_blog, name='post_blog'),
    url(r'^comment/(?P<url_key>[0-9])/$', views.comment, name='comment'),
    url(r'^reg_user/$', views.reg_user, name='reg_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

04 - Django/blogsite/blogsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

04 - Django/blogsite/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField()

    def __str__(self):
        return f'{self.title} - {self.user}'


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500, blank=True, null=True)
    timestamp = models.DateTimeField()

    def __str__(self):
        return f'{self.user} - {self.timestamp}'

04 - Django/blogsite/blog/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from .models import BlogPost, Comment
import datetime


# function to get index page
def index(request):
    return render(request, 'blog/index.html')


# function to get login page
def login_page(request):
    return render(request, 'blog/login.html')


# function to login user, gets username and password from the page, makes an authentication request, if user is none
# returns login page with error message, otherwise returns profile page
def login_user(request):

    user_name = request.POST['user_name']
    user_pass = request.POST['user_pass']

    user = authenticate(request, username=user_name, password=user_pass)

    if user is None:
        return render(request, 'blog/login.html', {'message': 'Invalid username or password.'})
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('blog:profile'))


# function to return registration page
def register(request):
    return render(request, 'blog/register.html')


# function to register user, gets username, email and password, if username exists, returns registration page with an
# error, otherwise creates a new user object, adds user to commenter group, saves, returns profile page with
# welcome message
def reg_user(request):

    user_name = request.POST['user_name']
    user_email = request.POST['user_email']
    user_pass = request.POST['user_pass']

    if User.objects.filter(username=user_name).exists():
        return render(request, 'blog/register.html', {'message': 'Username Already Exists.'})
    else:
        user = User.objects.create_user(username=user_name, email=user_email, password=user_pass)
        group = Group.objects.get(name='commenter')
        user.groups.add(group)
        user.save()

        login(request, user)

        context = {'user_message': 'Welcome to Blog.'}

    return render(request, 'blog/profile.html', context)


# function to return profile page, gets date and time of user's last login and renders as a message
@login_required
def profile(request):

    last_login = request.user.last_login
    context = {'user_message': 'Your last login was ', 'last_login': last_login}

    return render(request, 'blog/profile.html', context)


# function to logout user, returns login page with message that user has been logged out
@login_required
def logout_user(request):
    logout(request)
    return render(request, 'blog/login.html', {'message': 'You have been logged out.'})


# function to get list of available blog posts. requests all blog posts from model and passes them to be
# rendered in template
@login_required
def post_list(request):

    posts = BlogPost.objects.all()
    context = {'posts': posts}

    return render(request, 'blog/post_list.html', context)


# function to view blog post, gets id of post from url, requests post from model, requests comments from model,
# passes both to template to be rendered
@login_required
def post_detail(request, url_key):

    post = BlogPost.objects.get(id=url_key)

    comments = Comment.objects.filter(post=url_key)

    context = {'post': post, 'comments': comments}

    return render(request, 'blog/post_detail.html', context)


# function to post comment on blog post, gets comment from page, creates comment object and saves,
# redirects to same post
@login_required
def comment(request, url_key):

    page_comment = request.POST['comment']

    url_item = Comment(body=page_comment, post=BlogPost.objects.get(id=url_key), user=request.user, timestamp=datetime.datetime.now())
    url_item.save()

    return HttpResponseRedirect(reverse('blog:post_detail', args=url_key))


# function for blog composition, checks if user has permissions, if they do, render composition page, if not
# forward to profile page with error message
def post_compose(request):

    if request.user.has_perm('blog.poster'):
        return render(request, 'blog/post_compose.html')
    else:
        context = {'user_message': 'You don\'t have permission to post.'}

        return render(request, 'blog/profile.html', context)


# function to post new blog article, gets title and body of post from page, creates new blogpost object and saves,
# then redirects to post list
@permission_required('blog.poster')
def post_blog(request):

    post_title = request.POST['post_title']
    post_body = request.POST['post_body']

    blog_article = BlogPost(user=request.user, title=post_title, body=post_body, timestamp=datetime.datetime.now())
    blog_article.save()

    return HttpResponseRedirect(reverse('blog:post_list'))

04 - Django/blogsite/blog/templates/blog/index.html
<title>Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
h1 {
    font-size: 1.25em;
}
p {
    padding-top: 15px;
    font-size: .7em;
}
a:link {
    text-decoration: none;
}
</style>

<h1>Blog</h1>
<div id="container">
    <p>A simple blog. <a href="{% url 'blog:register' %}"><b>Create</b></a> an account or <a href="{% url 'blog:login' %}"><b>login</b></a> if you already have one.</p>
</div>

04 - Django/blogsite/blog/templates/blog/login.html
<title>Login | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 20px 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#message {
    padding-bottom: 10px;
    font-size: .7em;
}
h1 {
    font-size: 1.25em;
}
form {
    font-size: .7em;
    display: inline-block;

}
#form_container {
    text-align: left;
}
input[name=user_name] {
    margin-bottom: 4px;
}
</style>

<h1>Login</h1>
<div id="container">
    {% if message %}
    <div id="message" style="color:red">{{message}}</div>
    {% endif %}
    <form action="{% url 'blog:login_user' %}" method="POST">
        {% csrf_token %}
        <div id="form_container">
            User Name:<br>
            <input name="user_name" type="text">
            <br>
            Password:<br>
            <input name="user_pass" type="password">
        </div>
        <br>
        <button type="submit">Login</button>
    </form>
</div>

04 - Django/blogsite/blog/templates/blog/post_compose.html
<title>New Post | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#inner_container {
    font-size: .7em;
    width: 30%;
    margin: 10px auto 20px auto;
    padding: 5px 10px 5px 10px;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: flex;
    justify-content: space-evenly;
}
#inner_container a{
    text-decoration: none;
}
h1 {
    font-size: 1.25em;
}
span {
    font-size: .75em;
}
input[name="post_title"] {
    width: 70%;
    border: 1px solid #000;
}
textarea[name="post_body"] {
    margin-top: 10px;
    border: 1px solid #000;
}
</style>

<h1>New Post</h1>
<div id="container">
    <div id="inner_container">
        <b>Post</b><a href="{% url 'blog:post_list' %}">Browse</a><a href="{% url 'blog:profile' %}">Profile</a><a href="{% url 'blog:logout_user' %}">Log Out</a>
    </div>
    <div id="article_container"></div>
        <form action="{% url 'blog:post_blog' %}" method="post">
            {% csrf_token %}
            <span>Title: </span><input type="text" name="post_title"/>
            <textarea name="post_body" rows="30" cols="100"></textarea><br>
            <br>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

04 - Django/blogsite/blog/templates/blog/post_detail.html
<title>{{ post.title }} | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#inner_container {
    font-size: .7em;
    width: 30%;
    margin: 10px auto 20px auto;
    padding: 5px 10px 5px 10px;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: flex;
    justify-content: space-evenly;
}
#inner_container a{
    text-decoration: none;
}
#article_container {
    width: 90%;
    margin: 10px auto 20px auto;
}
#comment_container {
    width: 95%;
    margin: 10px auto 20px auto;
}
#comment_box {
    width: 95%;
}
h1 {
    font-size: 1.25em;
}
span {
    font-size: .75em;
}
p {
    text-align: left;
    font-size: .75em;
    margin: 10px auto 20px auto;
}
ul {
    padding: 0 20px 0 20px;
    text-align: left;
    list-style-type: none;
    font-size: .75em;
}
li {
    padding: 5px 5px 5px 5px;
}
ul li:nth-child(odd) {
    background-color: #e6e6e6;
}
ul li:nth-child(even) {
    background-color: #b5b5b5;
}
</style>

<h1>{{ post.title }}</h1>
<div id="container">
    <div id="inner_container">
        <a href="{% url 'blog:post_compose' %}">Post</a><a href="{% url 'blog:post_list' %}">Browse</a><a href="{% url 'blog:profile' %}">Profile</a><a href="{% url 'blog:logout_user' %}">Log Out</a>
    </div>
    <span>by {{ post.user }} - {{ post.timestamp }}</span>
    <div id="article_container"><p>{{ post.body|linebreaks }}</p></div>
    <div id="comment_container">
        <span>Comments:</span>
        <ul id="comments">
            {% for comment in comments %}
            <li>{{ comment.body }}<br><b>{{ comment.user }}, {{ comment.timestamp }}</b></li>
            {% endfor %}
        </ul>
        <br>
        <form action="{% url 'blog:comment' post.id %}" method="post">
            {% csrf_token %}
            <textarea id="comment_box" name="comment" rows="4" cols="100"></textarea><br>
            <br>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

04 - Django/blogsite/blog/templates/blog/post_list.html
<title>Browse Posts | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#inner_container {
    font-size: .7em;
    width: 30%;
    margin: 10px auto 20px auto;
    padding: 5px 10px 5px 10px;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: flex;
    justify-content: space-evenly;
}
#inner_container a{
    text-decoration: none;
}
h1 {
    font-size: 1.25em;
}
ul {
    text-align: left;
    list-style-type: none;
    padding: 20px 20px 10px 20px;
    font-size: .75em;
}
li {
    padding: 5px 5px 5px 5px;
}
ul li:nth-child(odd) {
    background-color:#e6e6e6;
}
ul li:nth-child(even) {
    background-color: #b5b5b5;
}
</style>

<h1>Browse Posts</h1>
<div id="container">
    <div id="inner_container">
        <a href="{% url 'blog:post_compose' %}">Post</a><b>Browse</b><a href="{% url 'blog:profile' %}">Profile</a><a href="{% url 'blog:logout_user' %}">Log Out</a>
    </div>
    <ul id="posts">
        {% for post in posts %}
        <li><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}, {{ post.user }}, {{ post.timestamp }}</a></li>
        {% endfor %}
    </ul>
</div>

04 - Django/blogsite/blog/templates/blog/profile.html
<title>Profile | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#inner_container {
    font-size: .7em;
    width: 30%;
    margin: 10px auto 20px auto;
    padding: 5px 10px 5px 10px;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: flex;
    justify-content: space-evenly;

}
#user_message {
    font-size: .7em;
  }
#inner_container a{
    text-decoration: none;
}
h1 {
    font-size: 1.25em;
}
</style>

<h1>Welcome {{request.user.username}}</h1>
<div id="container">
    <div id="inner_container">
        <a href="{% url 'blog:post_compose' %}">Post</a><a href="{% url 'blog:post_list' %}">Browse</a><b>Profile</b><a href="{% url 'blog:logout_user' %}">Log Out</a>
    </div>
    <div id="user_message">
        {{user_message}}{{last_login}}
    </div>
</div>

04 - Django/blogsite/blog/templates/blog/register.html
<title>Register | Blog</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 20px 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
#message {
    padding-bottom: 10px;
    font-size: .7em;
}
h1 {
    font-size: 1.25em;
}
form {
    font-size: .7em;
    display: inline-block;

}
#form_container {
    text-align: left;
}
input[name=user_name] {
    margin-bottom: 4px;
}
input[name=user_email] {
    margin-bottom: 4px;
}
</style>

<h1>Register</h1>
<div id="container">
    {% if message %}
    <div id="message" style="color:red">{{message}}</div>
    {% endif %}
    <form action="{% url 'blog:reg_user' %}" method="POST">
        {% csrf_token %}
        <div id="form_container">
            User Name:<br>
            <input name="user_name" type="text">
            <br>
            Email Address:<br>
            <input name="user_email" type="text">
            <br>
            Password:<br>
            <input name="user_pass" type="password">
        </div>
        <br>
        <button type="submit">Register</button>
    </form>
</div>