04 - Django/mainsite/library/urls.py
from django.conf.urls import url
from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/$', views.update, name='update'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^check_out/$', views.check_out, name='check_out'),
    url(r'^check_in/$', views.check_in, name='check_in'),
]

04 - Django/mainsite/mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^url_short/', include('url_short.urls')),
    url(r'^library/', include('library.urls')),
]

04 - Django/mainsite/todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^savetodo/$', views.savetodo, name='savetodo'),
    url(r'^completetodo/$', views.completetodo, name='completetodo'),
]

04 - Django/mainsite/library/models.py
from django.db import models


class Author(models.Model):
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    pub_date = models.DateField()
    checked_out = models.BooleanField()

    def __str__(self):
        return f'{self.title} - {self.author}'


class Checkouts(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.CharField(max_length=100)
    check_out = models.DateField()
    check_in = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.user} : {self.check_out} - {self.check_in}'

04 - Django/mainsite/library/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Book, Checkouts
import datetime


# function for index page, get all books from the model, store in context dict and pass to render with index template
def index(request):

    books = Book.objects.all()
    context = {'books': books}

    return render(request, 'library/index.html', context)


# function to update the model, gets all 'checked out' books as book update, gets all books from model as all books.
# loops through all books if book is in checked out books, marks it as checked out and breaks inner loop, otherwise
# book is marked as not checked out
def update(request):
    book_update = request.POST.getlist('books')
    all_books = Book.objects.all()

    for book in all_books:
        for title in book_update:
            if str(book) == str(title):
                book.checked_out = True
                book.save()
                break
            book.checked_out = False
            book.save()

    return HttpResponseRedirect(reverse('library:index'))


# function for checkout page, gets list of completed checkouts, open checkouts and books available for checkout,
# stores them in a context dict and renders them with checkout template
def checkout(request):

    completed_checkouts = Checkouts.objects.exclude(check_in=None)
    open_checkouts = Checkouts.objects.filter(check_in=None)
    ready_books = Book.objects.filter(checked_out=False)

    context = {'ready_books': ready_books, 'open_checkouts': open_checkouts, 'completed_checkouts': completed_checkouts}

    return render(request, 'library/checkout.html', context)


# function for checking out a book, gets entered user name and book from template, checks if either are blank and
# responds with blank checkout page. then builds new Checkout object with book id, username and current date for
# checkout then saves object to model. then updates book in the book in Book model to be checked out and saves.
def check_out(request):
    user_name = request.POST.get('user_name')
    book = request.POST.get('book_id')

    if user_name == '' or book == 'blank':
        return HttpResponseRedirect(reverse('library:checkout'))

    new_checkout = Checkouts(book_id=book, user=user_name, check_out=datetime.datetime.today().strftime('%Y-%m-%d'))
    new_checkout.save()

    update_book = Book.objects.get(id=book)
    update_book.checked_out = True
    update_book.save()

    return HttpResponseRedirect(reverse('library:checkout'))


# function for checking in books, gets checked items from list in template, loops over the list, gets checkout by
# book id and no check in, enters todays date as check in and saves. then gets book from book model, marks not
# as checked out and saves
def check_in(request):

    books_out = request.POST.getlist('checked_out')

    for book in books_out:

        open_checkout = Checkouts.objects.get(book_id=book, check_in=None)
        open_checkout.check_in = datetime.datetime.today().strftime('%Y-%m-%d')
        open_checkout.save()

        update_book = Book.objects.get(id=book)
        update_book.checked_out = False
        update_book.save()

    return HttpResponseRedirect(reverse('library:checkout'))

04 - Django/mainsite/library/templates/library/checkout.html
<title>Library Checkout</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 5px 0 20px 0;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: inline-block;
}
#inner_container {
    width: 80%;
    margin: 10px auto 20px auto;
    padding: 0 20px 0 20px;
    text-align: center;
    border: 1px solid #000;
    border-radius: 10px;
    display: block;
}
ul {
    text-align: left;
    list-style-type: none;
    padding: 0 20px 5px 20px;
    margin-bottom: 20px;
    font-size: .75em;
}
ul li:nth-child(odd) {
    background-color:lightgray;
}
li {
    padding-left: 5px;
}
h1 {
    font-size: 1.25em;
}
h3 {
    font-size: .9em;
    margin-bottom: 5px;
}
</style>

<h1>Library Checkout</h1>
<div id="container">
    <h3>New Checkout</h3>
    <div id="inner_container">
        <br>
        <form action="{% url 'library:check_out' %}" method="POST">
            {% csrf_token %}
            <input name="user_name" type="text" placeholder="First Name, Last Name">
                <select name="book_id">
                    <option value="blank" selected="selected">Select book</option>
                    {% for book in ready_books %}
                        <option value="{{ book.id }}">{{ book.title }}</option>
                    {% endfor %}
                </select>
            <br>
            <br>
            <button type="submit">Check Out</button>
        </form>
    </div>
    <h3>Open Checkouts</h3>
    <div id="inner_container">
        <br>
        <form action="{% url 'library:check_in' %}" method="POST">
            {% csrf_token %}
            <ul id="open_list">
                {% csrf_token %}
                {% for checkouts in open_checkouts %}
                <li><input type="checkbox" name="checked_out" value="{{ checkouts.book.id }}"/> <b>{{ checkouts.user }}</b>, {{ checkouts.book }}, <i>{{ checkouts.check_out }}</i></li>
                {% endfor %}
                </ul>
            <button type="submit">Check In</button>
        </form>
    </div>
    <h3>Completed Checkouts</h3>
    <div id="inner_container">
        <br>
        <ul id="completed_list">
            {% for checkouts in completed_checkouts %}
            <li><b>{{ checkouts.user }}</b>, {{ checkouts.book }}, <i>{{ checkouts.check_out }} - {{ checkouts.check_in }}</i></li>
            {% endfor %}
        </ul>
    </div>
</div>

04 - Django/mainsite/library/templates/library/index.html
<title>Library</title>
<style>
body {
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
}
#container {
    width: 60%;
    margin: 0;
    padding: 0 20px 20px 20px;
    text-align: center;
    border: 1px solid black;
    border-radius: 10px;
    display: inline-block;
}
ul {
    text-align: left;
    list-style-type: none;
    padding: 20px 20px 10px 20px;
    font-size: .75em;
}
ul li:nth-child(odd) {
    background-color:lightgray;
}
h1 {
    font-size: 1.25em;
}
</style>

<h1>Library</h1>
<div id="container">
    <form action="{% url 'library:update' %}" method="post">
        <ul id="books">
        {% csrf_token %}
        {% for book in books %}
            <li><input type="checkbox" name="books" value="{{ book.title }} - {{ book.author }}" {% if book.checked_out %}checked{% endif %}/> {{ book.title }}, {{ book.author }}, {{ book.pub_date }}</li>
        {% endfor %}
        </ul>
        <button type="submit">Update</button>
    </form>
</div>